/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PostType = IDL.Variant({
  'video' : IDL.Null,
  'text' : IDL.Null,
  'image' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Comment = IDL.Record({
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const FollowerCounts = IDL.Record({
  'followers' : IDL.Nat,
  'following' : IDL.Nat,
});
export const ReactionCount = IDL.Record({
  'count' : IDL.Nat,
  'reactionType' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Video = IDL.Record({
  'id' : IDL.Text,
  'url' : ExternalBlob,
  'title' : IDL.Text,
  'likes' : IDL.Nat,
  'uploader' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addReaction' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'doubleTapToLike' : IDL.Func([IDL.Text], [], []),
  'getAllPosts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, PostType))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
  'getFollowerCounts' : IDL.Func([IDL.Principal], [FollowerCounts], ['query']),
  'getLikes' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getPostType' : IDL.Func([IDL.Text], [IDL.Opt(PostType)], ['query']),
  'getReactionCounts' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ReactionCount)],
      ['query'],
    ),
  'getTrending' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideo' : IDL.Func([IDL.Text], [Video], ['query']),
  'getVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFollowing' : IDL.Func(
      [IDL.Principal, IDL.Principal],
      [IDL.Bool],
      ['query'],
    ),
  'likeVideo' : IDL.Func([IDL.Text], [], []),
  'registerPost' : IDL.Func([IDL.Text, PostType], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleFollow' : IDL.Func([IDL.Principal], [], []),
  'uploadVideo' : IDL.Func([IDL.Text, ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PostType = IDL.Variant({
    'video' : IDL.Null,
    'text' : IDL.Null,
    'image' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Comment = IDL.Record({
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const FollowerCounts = IDL.Record({
    'followers' : IDL.Nat,
    'following' : IDL.Nat,
  });
  const ReactionCount = IDL.Record({
    'count' : IDL.Nat,
    'reactionType' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Video = IDL.Record({
    'id' : IDL.Text,
    'url' : ExternalBlob,
    'title' : IDL.Text,
    'likes' : IDL.Nat,
    'uploader' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addReaction' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'doubleTapToLike' : IDL.Func([IDL.Text], [], []),
    'getAllPosts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, PostType))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
    'getFollowerCounts' : IDL.Func(
        [IDL.Principal],
        [FollowerCounts],
        ['query'],
      ),
    'getLikes' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getPostType' : IDL.Func([IDL.Text], [IDL.Opt(PostType)], ['query']),
    'getReactionCounts' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ReactionCount)],
        ['query'],
      ),
    'getTrending' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideo' : IDL.Func([IDL.Text], [Video], ['query']),
    'getVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFollowing' : IDL.Func(
        [IDL.Principal, IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'likeVideo' : IDL.Func([IDL.Text], [], []),
    'registerPost' : IDL.Func([IDL.Text, PostType], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleFollow' : IDL.Func([IDL.Principal], [], []),
    'uploadVideo' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };